
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: jwt
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/chang?serverTimezone=Asia/Seoul
    username: admin
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8001
